In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

![title](degree_centrality_graph.png)

In [2]:
title = {}

for i in range(97,109):
    char = chr(i)
    title[char] = i-97


print(title)
print(len(title))

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11}
12


In [3]:
# w.r.t out degree

adj_mat = np.zeros((12,12))

adj_mat[title['a'], title['e']] = 1
adj_mat[title['a'], title['j']] = 1
adj_mat[title['a'], title['l']] = 1

adj_mat[title['b'], title['a']] = 1

adj_mat[title['c'], title['b']] = 1
adj_mat[title['c'], title['d']] = 1

adj_mat[title['d'], title['h']] = 1

adj_mat[title['e'], title['g']] = 1

adj_mat[title['f'], title['b']] = 1
adj_mat[title['f'], title['g']] = 1

adj_mat[title['g'], title['b']] = 1
adj_mat[title['g'], title['c']] = 1
adj_mat[title['g'], title['h']] = 1
adj_mat[title['g'], title['j']] = 1

adj_mat[title['h'], title['g']] = 1
adj_mat[title['h'], title['d']] = 1
adj_mat[title['h'], title['k']] = 1

adj_mat[title['i'], title['a']] = 1
adj_mat[title['i'], title['j']] = 1

adj_mat[title['k'], title['j']] = 1

adj_mat[title['l'], title['a']] = 1

In [4]:
print(adj_mat)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
one_vec = np.ones((12,1)).reshape(12)

In [6]:
# Calculate inDegree centrality vector
in_deg_vec = np.matmul(adj_mat.transpose(), one_vec)

print("In Degree Vector: ", in_deg_vec)

In Degree Vector:  [3. 3. 1. 2. 1. 0. 3. 2. 0. 4. 1. 1.]


In [7]:
# Calculate outDegree centrality vector
out_deg_vec = np.matmul(adj_mat, one_vec)

print("Out Degree Vector: ", out_deg_vec)

Out Degree Vector:  [3. 1. 2. 1. 1. 2. 4. 3. 2. 0. 1. 1.]
