In [2]:
import nashpy as nash
import numpy as np

In [19]:
A = np.array([[3,1],[2,3]]) # A is the row player
B = np.array([[1,2],[4,1]]) # B is the column player
# A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
# B = - A

In [20]:
game1 = nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [2 3]]

Column player:
[[1 2]
 [4 1]]

In [21]:
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.75, 0.25]), array([0.66666667, 0.33333333]))
