# Confusion matrix evaluation

In [1]:
# TP_apple = 33
# FP_apple = 8 + 9
# TN_apple = 40 + 4 + 5 + 27
# FN_apple = 6 + 18

TP_apple = 46
FP_apple = 9 + 2
TN_apple = 61 + 0 + 3 + 25
FN_apple = 12 + 2

In [2]:
# TP_banana = 40
# FP_banana = 6 + 4
# TN_banana = 33 + 9 + 18 + 27
# FN_banana = 8 + 5

TP_banana = 61
FP_banana = 12 + 3
TN_banana = 46 + 2 + 2 + 25
FN_banana = 9 + 0

In [3]:
# TP_pear = 27
# FP_pear = 18 + 5
# TN_pear = 33 + 8 + 6 + 40
# FN_pear = 9 + 4

TP_pear = 25
FP_pear = 2 + 0
TN_pear = 46 + 12 + 9 + 3
FN_pear = 2 + 3

### Precision of Apple

In [4]:
precision_apple = (TP_apple) / (TP_apple + FP_apple)
precision_apple

0.8070175438596491

### Precision of Banana

In [5]:
precision_banana = (TP_banana) / (TP_banana + FP_banana)
precision_banana

0.8026315789473685

### Precision of Pear

In [6]:
precision_pear = (TP_pear) / (TP_pear + FP_pear)
precision_pear

0.9259259259259259

### Recall of Apple

In [7]:
recall_apple = (TP_apple) / (TP_apple + FN_apple)
recall_apple

0.7666666666666667

### Recall of Banana

In [8]:
recall_banana = (TP_banana) / (TP_banana + FN_banana)
recall_banana

0.8714285714285714

### Recall of Pear

In [9]:
recall_pear = (TP_pear) / (TP_pear + FN_pear)
recall_pear

0.8333333333333334

### F1-Score of Apple

In [10]:
f1_apple = 2 * ((precision_apple * recall_apple) / (precision_apple + recall_apple))
f1_apple

0.7863247863247863

### F1-Score of Banana

In [11]:
f1_banana = 2 * ((precision_banana * recall_banana) / (precision_banana + recall_banana))
f1_banana

0.8356164383561644

### F1-Score of Pear

In [12]:
f1_pear = 2 * ((precision_pear * recall_pear) / (precision_pear + recall_pear))
f1_pear

0.8771929824561403

### Micro Avg. Precision

In [13]:
micro_avg_precision = (TP_apple + TP_banana + TP_pear) / (TP_apple + FP_apple + TP_banana + FP_banana + TP_pear + FP_pear)
micro_avg_precision

0.825

### Micro Avg. Recall

In [14]:
micro_avg_recall = (TP_apple + TP_banana + TP_pear) / (TP_apple + FN_apple + TP_banana + FN_banana + TP_pear + FN_pear)
micro_avg_recall

0.825

### Micro Avg. F1-Score

In [15]:
micro_avg_f1 = 2 * ((micro_avg_precision * micro_avg_recall) / (micro_avg_precision + micro_avg_recall))
micro_avg_f1

0.825

### Macro Avg. Precision

In [16]:
macro_avg_precision = (precision_apple + precision_banana + precision_pear) / 3
macro_avg_precision

0.8451916829109812

### Macro Avg. Recall

In [17]:
macro_avg_recall = (recall_apple + recall_banana + recall_pear) / 3
macro_avg_recall

0.8238095238095239

### Macro Avg. F1-Score

In [20]:
# macro_avg_f1 = ((1/3) * f1_apple) + ((1/3) * f1_banana) + ((1/3) * f1_pear)
macro_avg_f1 = (f1_apple + f1_banana + f1_pear) / 3
macro_avg_f1

0.8330447357123637

### Avg. Accuracy

In [21]:
avg_acc = (TP_apple + TN_apple + TP_banana + TN_banana + TP_pear + TN_pear) / (TP_apple + TN_apple + FP_apple + FN_apple + 
 TP_banana + TN_banana + FP_banana + FN_banana + 
 TP_pear + TN_pear + FP_pear + FN_pear)

avg_acc

0.8672985781990521

### Error Rate

In [22]:
error = (FP_apple + FN_apple + FP_banana + FN_banana + FP_pear + FN_pear) / (TP_apple + TN_apple + FP_apple + FN_apple + 
 TP_banana + TN_banana + FP_banana + FN_banana + 
 TP_pear + TN_pear + FP_pear + FN_pear)

error

0.13270142180094788

In [23]:
avg_acc + error

1.0

### Overall Accuracy

In [25]:
overall_acc = (TP_apple + TP_banana + TP_pear) / (TP_apple + TN_apple + FP_apple + FN_apple)

overall_acc

0.825

# Likelihood

In [10]:
import numpy as np

In [11]:
male_weight = [57, 65, 76]
female_age = [20, 42, 27]

In [12]:
male_weight_mean = round(np.mean(male_weight), 2)
male_weight_pop_var = round(np.var(male_weight), 2)

print("Male Weight Mean:", male_weight_mean)
print("Male Weight Pop Var:", male_weight_pop_var)

Male Weight Mean: 66.0
Male Weight Pop Var: 60.67


In [13]:
female_age_mean = round(np.mean(female_age), 2)
female_age_pop_var = round(np.var(female_age), 2)

print("Female Age Mean:", female_age_mean)
print("Female Age Pop Var:", female_age_pop_var)

Female Age Mean: 29.67
Female Age Pop Var: 84.22


In [28]:
# P(weight|male)
exp_part = -(np.square(57 - male_weight_mean) / (2 * male_weight_pop_var))

p_W_given_Male = (1 / np.sqrt(2 * np.pi * male_weight_pop_var)) * np.exp(exp_part)

p_W_given_Male

0.02627311927107959

In [32]:
# P(age|female)
exp_part = -(np.square(23 - female_age_mean) / (2 * female_age_pop_var))

p_A_given_Female = (1 / np.sqrt(2 * np.pi * female_age_pop_var)) * np.exp(exp_part)

p_A_given_Female

0.03338068383899758

# Bernoulli Naive Baye's

In [1]:
play_Yes = 3 / 6
play_No = 3 / 6

rainy_No = 3 / 6
sunny_No = 3 / 6
windy_Yes = 3 / 6

In [2]:
p_NR_given_PY = 1 / 3
p_NS_given_PY = 1 / 3
p_YW_given_PY = 2 / 3

In [3]:
p_NR_given_PN = 2 / 3
p_NS_given_PN = 2 / 3
p_YW_given_PN = 1 / 3

In [4]:
p_X_Yes = p_NR_given_PY * p_NS_given_PY * p_YW_given_PY * play_Yes
p_X_No = p_NR_given_PN * p_NS_given_PN * p_YW_given_PN * play_No

print(p_X_Yes)
print(p_X_No)

0.037037037037037035
0.07407407407407407


In [5]:
p_X_est = rainy_No * sunny_No * windy_Yes
p_X_est

0.125

In [6]:
p_yes = p_X_Yes / p_X_est
p_no = p_X_No / p_X_est

print(p_yes)
print(p_no)

0.2962962962962963
0.5925925925925926


In [7]:
if p_yes > p_no:
    print("Play Football: Yes")
else:
    print("Play Football: NO")

Play Football: NO


## Using liberary

In [34]:
from sklearn.naive_bayes import BernoulliNB
from sklearn import preprocessing

In [33]:
rainy = ["Yes", "Yes", "No", "Yes", "No", "No"]
sunny = ["No", "No", "Yes", "Yes", "No", "Yes"]
windy = ["No", "Yes", "No", "Yes", "No", "Yes"]

play = ["No", "Yes", "Yes", "Yes", "No", "No"]

In [35]:
le = preprocessing.LabelEncoder()

In [36]:
r = le.fit_transform(rainy)
s = le.fit_transform(sunny)
w = le.fit_transform(windy)

labels = le.fit_transform(play)

In [37]:
features = list(zip(r, s, w))

In [46]:
le.classes_

array(['No', 'Yes'], dtype='<U3')

In [41]:
features

[(1, 0, 0), (1, 0, 1), (0, 1, 0), (1, 1, 1), (0, 0, 0), (0, 1, 1)]

In [52]:
model = BernoulliNB()
model.fit(features, labels)

BernoulliNB()

In [53]:
model.predict([[0, 0, 1]])

array([0])

In [54]:
model.predict_proba([[0, 0, 1]])

array([[0.6, 0.4]])

# KNN

In [17]:
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [18]:
income_labels = ["high", "high", "high", "low", "low", "high"]

height = [5.3, 5.7, 5.11, 5.1, 4.2, 5.6]
weight = [67, 76, 58, 62, 67, 89]
age = [22, 27, 26, 21, 23, 24]

In [19]:
le = preprocessing.LabelEncoder()

In [20]:
label = le.fit_transform(income_labels)

In [24]:
label

array([0, 0, 0, 1, 1, 0])

In [25]:
le.classes_

array(['high', 'low'], dtype='<U4')

In [26]:
features = list(zip(height, weight, age))

In [27]:
features

[(5.3, 67, 22),
 (5.7, 76, 27),
 (5.11, 58, 26),
 (5.1, 62, 21),
 (4.2, 67, 23),
 (5.6, 89, 24)]

In [28]:
model = KNeighborsClassifier(n_neighbors=3, metric="euclidean")

In [29]:
model.fit(features,label)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [30]:
predicted = model.predict([[5.8, 80, 27]])

In [31]:
print(predicted)

[0]


# Naive Baye's with smoothing

In [55]:
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import CategoricalNB

In [56]:
fever = ["High", "Mild", "Low", "Low", "High", "Low"]
cough = ["Yes", "No", "No", "Yes", "Yes", "No"]
cold = ["No", "Yes", "No", "Yes", "Yes", "Yes"]
stomach_ache = ["Severe", "Mild", "Severe", "Severe", "Mild", "Mild"]

covid = ["Yes", "No", "No", "Yes", "Yes", "No"]

In [57]:
le = preprocessing.LabelEncoder()

In [58]:
fev = le.fit_transform(fever)
cgh = le.fit_transform(cough)
cld = le.fit_transform(cold)
ach = le.fit_transform(stomach_ache)

cov = le.fit_transform(covid)

In [59]:
le.classes_

array(['No', 'Yes'], dtype='<U3')

In [60]:
print("Fever:", fev)
print("Cough:", cgh)
print("Cold:", cld)
print("Ache:", ach)

print("Covid:", cov)

Fever: [0 2 1 1 0 1]
Cough: [1 0 0 1 1 0]
Cold: [0 1 0 1 1 1]
Ache: [1 0 1 1 0 0]
Covid: [1 0 0 1 1 0]


In [68]:
X = list(zip(fev, cgh, cld, ach))
y = cov

X

[(0, 1, 0, 1),
 (2, 0, 1, 0),
 (1, 0, 0, 1),
 (1, 1, 1, 1),
 (0, 1, 1, 0),
 (1, 0, 1, 0)]

In [93]:
clf = CategoricalNB(alpha=1)
clf.fit(X, y)

CategoricalNB(alpha=1)

In [94]:
print(clf.predict([(0, 0, 0, 0)]))

[0]


In [95]:
clf.predict_proba([(0, 0, 0, 0)])

array([[0.66666667, 0.33333333]])