In [2]:
import numpy as np
from scipy.stats import norm

In [3]:
np.set_printoptions(suppress=True)

### Calculate Normal distribution using liberary / Expectation

In [11]:
l = norm.pdf(162745 , loc = 188014.34 , scale = 52541.39 )
l

6.763652779492299e-06

In [ ]:
l1 = norm.pdf(163025 , loc = 188014.34 , scale = 52541.39 )
l1

In [8]:
l2 = norm.pdf(163025 , loc = 143104.34 , scale = 18330.95 )
l2

1.205817331422209e-05

In [9]:
l3 = norm.pdf(163025 , loc = 146148.34 , scale = 18628.83 )
l3

1.4207072653916401e-05

In [10]:
l1 / (l1 + l2 + l3)

0.20519521745002928

In [5]:
norm.pdf(124 , loc = 110 , scale = 20 )

0.015612696668338064

In [6]:
norm.pdf(124 , loc = 160 , scale = 20 )

0.003947507915044708

### Calculate Normal distributition manually

In [3]:
X = np.array([[157434, 261952, 144657, 118777, 147511, 163025, 120131, 162745, 155569]]).T

In [4]:
X

array([[157434],
       [261952],
       [144657],
       [118777],
       [147511],
       [163025],
       [120131],
       [162745],
       [155569]])

In [5]:
X_mean = X.mean()

In [6]:
means = [188014.34, 143104.34, 146148.34] 
stds = [52541.39, 18330.95, 18628.83]

In [7]:
# Q1
# xi = 162745
# xi = 163025

# Q2
# xi = 144657

In [8]:
def normal_distribution(x, mean, std):
    exp = np.exp(-0.5 * ((x - mean) / std) ** 2)
    
    # fd = std * np.sqrt(2 * np.pi)
    fd = np.sqrt(2 * np.pi * (std ** 2))
    
    return 1 / fd * exp

In [9]:
def calculate_weights(X, means, stds):
    z_weights = []

    for i in range(len(X)):
        lik1 = normal_distribution(X[i, 0], means[0], stds[0])
        lik2 = normal_distribution(X[i, 0], means[1], stds[1])
        lik3 = normal_distribution(X[i, 0], means[2], stds[2])

        z1 = lik1 / (lik1 + lik2 + lik3)
        z2 = lik2 / (lik2 + lik1 + lik3)
        z3 = lik3 / (lik3 + lik1 + lik2)

        z_weights.append([z1, z2, z3])
        
    return np.column_stack((X, z_weights))

In [12]:
print(calculate_weights(X, means, stds))

[[157434.              0.15917887      0.39816723      0.4426539 ]
 [261952.              0.99999996      0.00000001      0.00000003]
 [144657.              0.1115294       0.44773064      0.44073996]
 [118777.              0.1635436       0.46299864      0.37345776]
 [147511.              0.11717516      0.43918331      0.44364153]
 [163025.              0.20519522      0.36488879      0.42991599]
 [120131.              0.15476214      0.46600918      0.37922868]
 [162745.              0.20236856      0.3667766       0.43085483]
 [155569.              0.14802369      0.40742719      0.44454912]]


In [13]:
means = [188014.34, 143104.34, 146148.34] 
stds = [52541.39, 18330.95, 18628.83]

for i in range(10):
    X = calculate_weights(X, means, stds)
    
#     d = [item[0] for item in data]
#     z1 = [item[1] for item in data]
#     z2 = [item[2] for item in data]
#     z3 = [item[3] for item in data]
    
    new_mean1 = (np.sum(X[: , 0] * X[: , 1])) / np.sum(X[: , 1])
    new_mean2 = (np.sum(X[: , 0] * X[: , 2])) / np.sum(X[: , 2])
    new_mean3 = (np.sum(X[: , 0] * X[: , 3])) / np.sum(X[: , 3])

    new_std1 = np.sum((X[: , 1] * ((X[: , 0] - X_mean) ** 2))) / np.sum(X[: , 1])
    new_std2 = np.sum((X[: , 2] * ((X[: , 0] - X_mean) ** 2))) / np.sum(X[: , 2])
    new_std3 = np.sum((X[: , 3] * ((X[: , 0] - X_mean) ** 2))) / np.sum(X[: , 3])
    
    means[0] = new_mean1
    means[1] = new_mean2
    means[2] = new_mean3

    stds[0] = new_std1
    stds[1] = new_std2
    stds[2] = new_std3
    
    print(X)
    print("")
    print(f"m1 = {means[0]},     m2 = {means[1]},     m3 = {means[2]}")
    print(f"s1 = {np.sqrt(stds[0])},     m2 = {np.sqrt(stds[1])},     m3 = {np.sqrt(stds[2])}")
    print("-------------------------------------------------------")
    
    if new_mean1 == new_mean2 and new_mean1 == new_mean3 and new_mean2 == new_mean3 and new_std1 == new_std2 and new_std1 == new_std3 and new_std2 == new_std3:
        print("EM convereged at iteration #", i)
        break
        
    X = np.delete( X , 1 , 1 )
    X = np.delete( X , 1 , 1 )
    X = np.delete( X , 1 , 1 )
else:
    print("All iterations completed")

[[157434.              0.15917887      0.39816723      0.4426539 ]
 [261952.              0.99999996      0.00000001      0.00000003]
 [144657.              0.1115294       0.44773064      0.44073996]
 [118777.              0.1635436       0.46299864      0.37345776]
 [147511.              0.11717516      0.43918331      0.44364153]
 [163025.              0.20519522      0.36488879      0.42991599]
 [120131.              0.15476214      0.46600918      0.37922868]
 [162745.              0.20236856      0.3667766       0.43085483]
 [155569.              0.14802369      0.40742719      0.44454912]]

m1 = 198013.17153968776,     m2 = 144869.1700679799,     m3 = 147167.10635826318
s1 = 70144.6045085761,     m2 = 22037.617566611494,     m3 = 19991.486606998482
-------------------------------------------------------
[[157434.              0.04265792      0.43217432      0.52516776]
 [261952.              0.04265792      0.43217432      0.52516776]
 [144657.              0.04265792      0.432

### Example from slides

In [17]:
example_data = np.array([124, 115, 121, 139, 98, 135, 131, 170, 166, 155, 167, 158, 175, 143, 163, 160, 145, 176])

In [18]:
mean1 = 110
std1 = 20

mean2 = 160
std2 = 20

z1_weights = []
z2_weights = []

for d in example_data:
    lik1 = normal_distribution(d, mean1, std1)
    lik2 = normal_distribution(d, mean2, std2)

    z1 = lik1 / (lik1 + lik2)
    z2 = lik2 / (lik1 + lik2)

    z1_weights.append(z1)
    z2_weights.append(z2)

In [23]:
new_mean1 = sum(example_data * z1_weights) / sum(z1_weights)
new_mean2 = sum(example_data * z2_weights) / sum(z2_weights)

new_std1 = np.sqrt(np.sum(z1_weights * (example_data - new_mean1) ** 2) / np.sum(z1_weights))
new_std2 = np.sqrt(np.sum(z2_weights * (example_data - new_mean2) ** 2) / np.sum(z2_weights))

In [24]:
print(new_mean1)
print(new_mean2)
print("")
print(new_std1)
print(new_std2)

123.71818737103645
157.71494020291954

15.97500353136857
14.611975229184742


In [18]:
import numpy as np
# from sklearn.mixture import GaussianMixture
import math

np.set_printoptions(suppress=True)

def applyNormalDistribution(val , mean , stdDev):
    return (1 / (stdDev*np.sqrt(2.*math.pi)) ) * np.exp( -0.5 * ((val - mean) / stdDev) ** 2. )
    
x = np.array([[157434 , 261952 , 144657 , 118777 , 147511 , 163025 , 120131 , 162745 , 155569]]).T

mean1 , stdDev1 = 188014.34 , 52541.39
mean2 , stdDev2 = 143104.34 , 18330.95
mean3 , stdDev3 = 146148.34 , 18628.83

for i in range(10):
    weights = []
    for j in range( len(x) ):
        distValue1 = applyNormalDistribution( x[j , 0] , mean1 , stdDev1 )
        distValue2 = applyNormalDistribution( x[j , 0] , mean2 , stdDev2 )
        distValue3 = applyNormalDistribution( x[j , 0] , mean3 , stdDev3 )
        weights.append( [distValue1/(distValue1 + distValue2 + distValue3) , distValue2/(distValue2 + distValue1 + distValue3) , distValue3/(distValue3 + distValue1 + distValue2)] )
    x = np.column_stack( (x , weights) ) 
    print(x)
    mean1 = ( np.sum(x[: , 0] * x[: , 1]) ) / np.sum( x[: , 1] )
    mean2 = ( np.sum(x[: , 0] * x[: , 2]) ) / np.sum( x[: , 2] )
    mean3 = ( np.sum(x[: , 0] * x[: , 3]) ) / np.sum( x[: , 3] )
    stdDev1 = np.sum((x[: , 1] * (( x[: , 0] - mean1 )**2) ) ) / np.sum( x[: , 1] ) 
    stdDev2 = np.sum(( x[: , 2] * (( x[: , 0] - mean2 )**2) ) ) / np.sum( x[: , 2] ) 
    stdDev3 = np.sum(( x[: , 3] * (( x[: , 0] - mean3 )**2) ) ) / np.sum( x[: , 3] ) 
    
    print('Mean1: {} , Mean2: {} , Mean3: {}'.format(mean1 , mean2 , mean3))
    print('StdDev1: {} , StdDev2: {} , StdDev3: {}\n'.format(np.sqrt(stdDev1) , np.sqrt(stdDev2) , np.sqrt(stdDev3)))
    if mean1 == mean2 and mean1 == mean3 and mean2 == mean3 and stdDev1 == stdDev2 and stdDev1 == stdDev3 and stdDev2 == stdDev3:
        print('Convergence at iteration: {}'.format(i))
        break
    x = np.delete( x , 1 , 1 )
    x = np.delete( x , 1 , 1 )
    x = np.delete( x , 1 , 1 )
    
#print( np.column_stack( (x , weights) ) )
'''
val1 = applyNormalDistribution( x[0] , mean1 , stdDev1 )
val2 = applyNormalDistribution( x[0] , mean2 , stdDev2 )

print( '{:.5f} , {:.5f}'.format( val1 , val2 ) )
p1 = (val1)/(val1 + val2)
p2 = (val2)/(val2 + val1)
print('{:.4f} {:.4f}'.format( p1 , p2 ) )
'''  

[[157434.              0.15917887      0.39816723      0.4426539 ]
 [261952.              0.99999996      0.00000001      0.00000003]
 [144657.              0.1115294       0.44773064      0.44073996]
 [118777.              0.1635436       0.46299864      0.37345776]
 [147511.              0.11717516      0.43918331      0.44364153]
 [163025.              0.20519522      0.36488879      0.42991599]
 [120131.              0.15476214      0.46600918      0.37922868]
 [162745.              0.20236856      0.3667766       0.43085483]
 [155569.              0.14802369      0.40742719      0.44454912]]
Mean1: 198013.17153968776 , Mean2: 144869.17006797993 , Mean3: 147167.10635826318
StdDev1: 58353.87229322074 , StdDev2: 16836.063219073785 , StdDev3: 16047.67860947229

[[157434.              0.03811596      0.45789419      0.50398985]
 [261952.              0.03811596      0.45789419      0.50398985]
 [144657.              0.03811596      0.45789419      0.50398985]
 [118777.              0.0

"\nval1 = applyNormalDistribution( x[0] , mean1 , stdDev1 )\nval2 = applyNormalDistribution( x[0] , mean2 , stdDev2 )\n\nprint( '{:.5f} , {:.5f}'.format( val1 , val2 ) )\np1 = (val1)/(val1 + val2)\np2 = (val2)/(val2 + val1)\nprint('{:.4f} {:.4f}'.format( p1 , p2 ) )\n"