In [1]:
import numpy as np

In [2]:
true_A = [0] * 60
pred_A = ([0] * 46) + ([1] * 12) + ([2] * 2)

true_B = [1] * 70
pred_B = ([0] * 9) + ([1] * 61)

true_C = [2] * 30
pred_C = ([0] * 2) + ([1] * 3) + ([2] * 25)

In [3]:
true_Y = true_A + true_B + true_C
pred_Y = pred_A + pred_B + pred_C

In [4]:
class Evaluation:
    def __init__(self, pred_y, true_y):
        self.pred_y = pred_y
        self.true_y = true_y
        self.init_confussion_matrix()
        
    def init_confussion_matrix(self):
        matrix = np.stack((self.pred_y, self.true_y), axis=1)
        
        self.size = len(set(matrix[:, 0])) 
        self.con_mat = np.zeros((self.size, self.size))

        for i in range(matrix.shape[0]):
            self.con_mat[matrix[i, 1]][matrix[i, 0]] += 1
            
        self.TP = np.diag(self.con_mat)
        self.FP = self.con_mat.sum(axis=0) - np.diag(self.con_mat)
        self.FN = self.con_mat.sum(axis=1) - np.diag(self.con_mat)
        self.TN = self.con_mat.sum() - (self.TP + self.FP + self.FN)
        
        
    def getPrecision(self):
        return self.TP / (self.TP + self.FP)
    
    def getRecall(self):
        return self.TP / (self.TP + self.FN)
    
    def getAccuracy(self):
        return (self.TP + self.TN) / self.con_mat.sum()
    
    def getF1Score(self):
        precision = self.getPrecision()
        recall = self.getRecall()
        
        return 2 * (precision * recall) / (precision + recall)
    
    def printEvaluation(self):
        precision = self.getPrecision()
        recall = self.getRecall()
        f1Score = self.getF1Score()
        accuracy = self.getAccuracy()
        
        print("-" * 106)
        print("|{: ^20}|{: ^20}|{: ^20}|{: ^20}|{: ^20}|".format("Class", "Accuracy", "Precission", "Recall", "F1-Score"))
        for i in range(self.size):
            print("|{: >20}|{: >20.2f}|{: >20.2f}|{: >20.2f}|{: >20.2f}|".format(i+1, accuracy[i], precision[i], recall[i], f1Score[i]))
        
        print("-" * 106)

In [5]:
ev = Evaluation(pred_Y, true_Y)

In [6]:
ev.getPrecision()

array([0.80701754, 0.80263158, 0.92592593])

In [7]:
ev.getRecall()

array([0.76666667, 0.87142857, 0.83333333])

In [8]:
ev.getAccuracy()

array([0.84375, 0.85   , 0.95625])

In [9]:
ev.getF1Score()

array([0.78632479, 0.83561644, 0.87719298])

In [10]:
ev.printEvaluation()

----------------------------------------------------------------------------------------------------------
|       Class        |      Accuracy      |     Precission     |       Recall       |      F1-Score      |
|                   1|                0.84|                0.81|                0.77|                0.79|
|                   2|                0.85|                0.80|                0.87|                0.84|
|                   3|                0.96|                0.93|                0.83|                0.88|
----------------------------------------------------------------------------------------------------------
